# Generated by Django 5.1.4 on 2025-04-06 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_otherimages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='indication',
        ),
    ]
