# Generated by Django 5.1.4 on 2025-04-06 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_description_product_indication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='indication',
            new_name='description',
        ),
    ]
